services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - es
    environment:
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_NAME=yuquepp
      - REDIS_HOST=redis
      - ES_HOST=es
    volumes:
      - ./data/app:/app/data
      - /etc/localtime:/etc/localtime:ro  # 挂载宿主机时区文件
    restart: always

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"  # 映射 MySQL 的 3306 端口
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=yuquepp
    volumes:
      - db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # 映射 Redis 的 6379 端口
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: es
    ports:
      - "9200:9200"  # 映射 Elasticsearch 的 HTTP 端口
      - "9300:9300"  # 映射 Elasticsearch 的集群通信端口
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - xpack.security.enabled=false  # 关闭安全认证
      - xpack.security.http.ssl.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    restart: always

volumes:
  db_data: {}
  es_data: {}