services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - es
    environment:
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_NAME=yuquepp
      - REDIS_HOST=redis
      - ES_HOST=es
      - TZ=Asia/Shanghai  # 设置中国时区
    volumes:
      - ./data/app:/app/data
    restart: always

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
      MYSQL_DATABASE: yuquepp
      - TZ=Asia/Shanghai  # 设置中国时区
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - TZ=Asia/Shanghai  # 设置中国时区
    restart: always

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - TZ=Asia/Shanghai  # 设置中国时区
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always
