#server:
#  port: 8000
#database:
#  host: "db"  # 使用 mysql 服务的容器名 "db"
#  port: "3306"
#  user: "root"
#  password: "12345678"
#  dbname: "yuquepp"
#redis:
#  host: "redis"  # 使用 redis 服务的容器名 "redis"
#  port: "6379"
#  password: ""
#  db: 0
#document_store_path: "./data/document"
#elasticsearch:
#  address: "http://es:9200"  # 使用 Elasticsearch 服务的容器名 "es"

# 本地开发调试使用
server:
  port: 8000
database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "12345678"
  dbname: "yuquepp"
redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
document_store_path: "./data/document"
elasticsearch:
  address: "http://localhost:9200"
