server:
  port: 8000
database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "12345678"
  dbname: "yuquepp"
redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
document_store_path: "/Users/gaotianhe/storageFile/document"
elasticsearch:
  address: "http://localhost:9200"